{
 "title": "ERC-20 Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(erc20_transfer_event_bucket,  job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(erc20_transfer_event_bucket, instance)"
    }
   },
   {
    "name": "blockchain",
    "label": "blockchain",
    "query": {
     "query": "label_values(erc20_transfer_event_bucket, blockchain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ERC20", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transfer events transaction rate",
   "type": "timeseries",
   "description": "Transfer transactions emitted over time.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "tx / sec" } },
   "targets": [
    {
     "expr": "sum by (symbol, contract) (\n    rate(erc20_transfer_event_count{instance=~\"$instance\", job=~\"$job\", blockchain=~\"$blockchain\"}[$__rate_interval])\n  )",
     "legendFormat": "{{ symbol }}"
    }
   ]
  },
  {
   "title": "Transferred Volume",
   "type": "timeseries",
   "description": "Total volume transacted over time.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (contract, symbol) (\n    erc20_transfer_event_sum{instance=~\"$instance\", job=~\"$job\", blockchain=~\"$blockchain\"}\n  )",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  { "title": "Blockchain Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "latest block number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_block_number{instance=~\"$instance\", job=~\"$job\", blockchain=~\"$blockchain\"}"
    }
   ]
  },
  {
   "title": "Current Gas Price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_gas_price{job=~\"$job\", instance=~\"$instance\", blockchain=~\"$blockchain\"} * 0.00000001"
    }
   ]
  },
  {
   "title": "Pending Block Transactions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_pending_block_transactions{instance=~\"$instance\", job=~\"$job\", blockchain=~\"$blockchain\"} "
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_peers{instance=~\"$instance\", job=~\"$job\", blockchain=~\"$blockchain\"}"
    }
   ]
  }
 ]
}